### ISSUE TITLE
[Feature] Wallbox als On/Off Switch

### ISSUE THREAD

**Issue by Trustmania** [derolli1976/enpal#16]
### Dein Vorschlag

Juten Morgen, 

wie schon mehrmals geschrieben, nochmal vielen Dank für den ganzen drive, die du in die Geschichte hier bringst. Extrem gut!

Zur Feature Idee: Wäre es nicht sinnvoll, die Wallbox als Switch abzubilden? Der "Stateless" Button ist erstmal ok für die erste Abbildung, weil wir generell die Möglichkeit bekommen haben, die Wallbox in HA einzubinden, ich denke aber einen Switch, der den Status auch abbildet wäre genialer, besonders auch für Automatisierungen.

So kann man sich einfache Automatisierungen machen wie z.b.:

`WENN wallbox == on UND PV < 3kW UND Speicher < 80% DANN wallbox = off`

Ähnliches wäre natürlich auch für den Modus cool. (Obwohl mir das nahezu egal ist, weil ich zu 99,99% eh im Solar Modus lade :-P )

Den Modus könnte man (zusätzlich) über ein input_select abbilden:

```
input_select:
  wallbox_modus:
    name: Wallboxmodus
    options:
      - "Solar"
      - "Evo"
      - "Full"
    initial: "Solar"
```

### Betrifft dein Wunsch die Wallbox-Steuerung?

Ja :-) 

---
